"""Typed human-governance policy infrastructure.

This package is deliberately separate from order submission.  It can produce
an auditable governance decision, but it cannot create, route, cancel, or
authorize an order and it cannot loosen the deterministic RiskKernel.
"""

from .authorization import (
    HUMAN_ONLY_ACTIONS,
    ActorType,
    AuthorizationExpiryMode,
    HumanAuthorization,
    authorization_is_valid,
    is_human_only_action,
)
from .decisions import (
    ActionDirection,
    CalibratedConfidenceEvidence,
    CertaintyClass,
    DecisionImpact,
    DecisionOutcome,
    EquitySnapshot,
    GovernanceDecision,
    GovernanceEvidence,
    GovernanceRequest,
    GovernanceRiskSnapshot,
    ReasonCode,
    RiskState,
    TimingClass,
    evaluate_governance,
    evaluate_live_activation,
)
from .policy import (
    AggregateGroupExposureLimit,
    AllocationStage,
    CorrelatedExposureGroup,
    GovernancePolicy,
    LiveActivationInput,
    PositionSizingInput,
    PositionSizingResult,
    apply_quarter_kelly,
    load_governance_policy,
)
from .scope import (
    DEFAULT_ACTION_AUTHORITY_MATRIX,
    ActionMatrixEntry,
    AssetClass,
    AuthorityClass,
    CredentialCapability,
    CredentialCapabilitySet,
    EligibilityTier,
    HumanAuthorizationState,
    MarketType,
    ModelLifecycle,
    PositionDirection,
    ScopeAction,
    ScopeAssetClass,
    ScopeClass,
    ScopeDecisionOutcome,
    ScopeReasonCode,
    StrategyLifecycle,
    TradingCapability,
    TradingScopeDecision,
    TradingScopePolicy,
    TradingScopeRequest,
    evaluate_trading_scope,
    load_trading_scope_policy,
)

__all__ = [
    "ActionDirection",
    "ActionMatrixEntry",
    "AssetClass",
    "ActorType",
    "AggregateGroupExposureLimit",
    "AllocationStage",
    "AuthorityClass",
    "AuthorizationExpiryMode",
    "CalibratedConfidenceEvidence",
    "CredentialCapability",
    "CredentialCapabilitySet",
    "DEFAULT_ACTION_AUTHORITY_MATRIX",
    "EligibilityTier",
    "CertaintyClass",
    "CorrelatedExposureGroup",
    "DecisionImpact",
    "DecisionOutcome",
    "EquitySnapshot",
    "GovernanceDecision",
    "GovernanceEvidence",
    "GovernancePolicy",
    "GovernanceRequest",
    "GovernanceRiskSnapshot",
    "HumanAuthorizationState",
    "HUMAN_ONLY_ACTIONS",
    "HumanAuthorization",
    "LiveActivationInput",
    "MarketType",
    "ModelLifecycle",
    "PositionSizingInput",
    "PositionSizingResult",
    "PositionDirection",
    "ScopeAssetClass",
    "ReasonCode",
    "RiskState",
    "ScopeAction",
    "ScopeClass",
    "ScopeDecisionOutcome",
    "ScopeReasonCode",
    "StrategyLifecycle",
    "TimingClass",
    "TradingCapability",
    "TradingScopeDecision",
    "TradingScopePolicy",
    "TradingScopeRequest",
    "apply_quarter_kelly",
    "authorization_is_valid",
    "evaluate_governance",
    "evaluate_live_activation",
    "load_governance_policy",
    "load_trading_scope_policy",
    "is_human_only_action",
    "evaluate_trading_scope",
]
