"""Replaceable model gateway adapters with explicit route/fallback records."""

from advisorai.ports import (
    GATEWAY_OUTPUT_SCHEMAS,
    Claim,
    ClaimList,
    CodePatchProposal,
    Counterargument,
    DataClassification,
    DecisionImpact,
    GatewayDataClass,
    GatewayOutputKind,
    GatewayTier,
    GenericOutput,
    NewsExtraction,
    ResearchQuestion,
    RouteTier,
    validate_gateway_output,
)

from .adapters import (
    DirectProviderGatewayAdapter,
    LiteLLMGatewayAdapter,
    OmniRouteGatewayAdapter,
    TypedGatewayAdapter,
)
from .core import (
    GatewayAttempt,
    GatewayCallRecord,
    GatewayChain,
    GatewayFailure,
    GatewayRecorder,
    LocalDeterministicGateway,
)
from .policy import (
    GatewayDecision,
    GatewayPolicyConfig,
    GatewayPolicyError,
    ModelGateway,
    PolicyGateway,
    ProviderRoutePolicy,
    ProviderTerms,
    RouteProfile,
    ThreeTierModelGateway,
    classify_payload,
    contains_secret_material,
    redact_request,
    redact_text,
)

__all__ = [
    "DirectProviderGatewayAdapter",
    "GatewayAttempt",
    "GatewayCallRecord",
    "GatewayChain",
    "GatewayFailure",
    "GatewayRecorder",
    "GatewayDecision",
    "GatewayDataClass",
    "GenericOutput",
    "NewsExtraction",
    "Claim",
    "ClaimList",
    "CodePatchProposal",
    "ResearchQuestion",
    "Counterargument",
    "GATEWAY_OUTPUT_SCHEMAS",
    "validate_gateway_output",
    "GatewayOutputKind",
    "GatewayPolicyConfig",
    "GatewayPolicyError",
    "GatewayTier",
    "DataClassification",
    "DecisionImpact",
    "RouteTier",
    "LiteLLMGatewayAdapter",
    "OmniRouteGatewayAdapter",
    "LocalDeterministicGateway",
    "ModelGateway",
    "PolicyGateway",
    "ProviderRoutePolicy",
    "ProviderTerms",
    "RouteProfile",
    "ThreeTierModelGateway",
    "TypedGatewayAdapter",
    "classify_payload",
    "contains_secret_material",
    "redact_request",
    "redact_text",
]
