"""Phase-4 paper-utility contracts and deterministic evaluation helpers."""

from .paper_utility import (
    CANDIDATE_MODELS,
    MANDATORY_BASELINES,
    Phase4EvaluationReport,
    Phase4EvaluationState,
    Phase4MarketObservation,
    Phase4Prediction,
    Phase4PrerequisiteError,
    Phase4UtilityPolicy,
    Phase4UtilityResult,
    build_preparation_manifest,
    evaluate_paper_utility,
)
from .signal_policy import (
    PolicyPathComparison,
    PolicySignal,
    PolicySliceMetric,
    PolicyUtilityMetrics,
    PredictionDistributionSummary,
    SignalCostScenario,
    SignalPolicyFamily,
    SignalPolicySpec,
    apply_signal_policy,
    candidate_policy_specs,
    compare_policy_paths,
    evaluate_policy_signals,
    summarize_prediction_distribution,
)

__all__ = [
    "CANDIDATE_MODELS",
    "MANDATORY_BASELINES",
    "Phase4EvaluationReport",
    "Phase4EvaluationState",
    "Phase4MarketObservation",
    "Phase4Prediction",
    "Phase4PrerequisiteError",
    "Phase4UtilityPolicy",
    "Phase4UtilityResult",
    "build_preparation_manifest",
    "evaluate_paper_utility",
    "PolicyPathComparison",
    "PolicySignal",
    "PolicySliceMetric",
    "PolicyUtilityMetrics",
    "PredictionDistributionSummary",
    "SignalCostScenario",
    "SignalPolicyFamily",
    "SignalPolicySpec",
    "apply_signal_policy",
    "candidate_policy_specs",
    "compare_policy_paths",
    "evaluate_policy_signals",
    "summarize_prediction_distribution",
]
